### ISSUE TITLE
Paco dataset online visualization website error：  https://paco-explore.metademolab.com/

### ISSUE THREAD

**Issue by wu467** [facebookresearch/paco#23] opened 2024-07-31 02:49 UTC
![图片](https://github.com/user-attachments/assets/0d367a46-ac8b-4db4-ba71-bfbaad866537)

The data set visualization website is down. Can you fix it? Thank you very much!

**Comment by anmolkalia** [comment] 2024-08-01 20:26
Thanks for letting us know. The issue is fixed now

**Closed as completed** 2024-08-01 20:26 UTC
